// backend/src/services/emailService.js
const nodemailer = require('nodemailer');

// Create transporter with Zoho SMTP settings
const createTransporter = () => {
  return nodemailer.createTransport({
    host: 'smtp.zoho.com', // Zoho SMTP server
    port: 465, // Use 587 for TLS, 465 for SSL
    secure: true, // true for 465, false for other ports
    auth: {
      user: process.env.ZOHO_EMAIL, // Your Zoho email (info@foveaopticals.com)
      pass: process.env.ZOHO_APP_PASSWORD // App-specific password (NOT your regular password!)
    },
    tls: {
      ciphers: 'SSLv3'
    }
  });
};

/**
 * Send new client registration notification
 */
const sendNewClientNotification = async (clientData) => {
  try {
    const transporter = createTransporter();
    
    const mailOptions = {
      from: `"Fovea Optical" <${process.env.ZOHO_EMAIL}>`, // Sender address
      to: process.env.ZOHO_EMAIL, // Send to yourself (info@foveaopticals.com)
      replyTo: clientData.email, // Client can reply directly
      subject: `📋 New Client Registration: ${clientData.name}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; }
            .header { background: #2563eb; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
            .content { background: #f8fafc; padding: 25px; border-radius: 0 0 8px 8px; }
            .details { background: white; border-radius: 6px; padding: 20px; margin: 20px 0; }
            table { width: 100%; border-collapse: collapse; }
            td { padding: 10px 0; border-bottom: 1px solid #e2e8f0; }
            .footer { margin-top: 30px; padding-top: 20px; border-top: 2px solid #e2e8f0; color: #64748b; font-size: 14px; }
            .button { display: inline-block; background: #2563eb; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; margin-top: 15px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2 style="margin: 0;">🎉 New Client Registration</h2>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">Fovea Optical Website</p>
          </div>
          
          <div class="content">
            <p>Hello Team,</p>
            <p>A new client has registered on the Fovea Optical website:</p>
            
            <div class="details">
              <h3 style="margin-top: 0; color: #475569;">Client Details</h3>
              <table>
                <tr>
                  <td><strong>👤 Name:</strong></td>
                  <td>${clientData.name}</td>
                </tr>
                <tr>
                  <td><strong>📧 Email:</strong></td>
                  <td><a href="mailto:${clientData.email}">${clientData.email}</a></td>
                </tr>
                <tr>
                  <td><strong>📱 Phone:</strong></td>
                  <td>${clientData.phone || 'Not provided'}</td>
                </tr>
                <tr>
                  <td><strong>📅 Registration Time:</strong></td>
                  <td>${new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })}</td>
                </tr>
              </table>
            </div>
            
            <a href="mailto:${clientData.email}" class="button">Reply to Client</a>
            
            <div class="footer">
              <p>This email was automatically generated by your Fovea Optical website.</p>
              <p><small>Client ID: ${clientData._id || 'N/A'}</small></p>
            </div>
          </div>
        </body>
        </html>
      `,
      text: `NEW CLIENT REGISTRATION\n\nName: ${clientData.name}\nEmail: ${clientData.email}\nPhone: ${clientData.phone || 'Not provided'}\nRegistration Time: ${new Date().toLocaleString('en-KE', { timeZone: 'Africa/Nairobi' })}\n\n---\nAutomated message from Fovea Optical website`
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('✅ Email sent successfully:', info.messageId);
    
    return {
      success: true,
      messageId: info.messageId,
      clientEmail: clientData.email
    };
    
  } catch (error) {
    console.error('❌ Email sending failed:', error);
    
    // Specific error handling for Zoho
    if (error.code === 'EAUTH') {
      console.error('⚠️ Authentication failed. Check Zoho email and app password.');
    } else if (error.code === 'ECONNECTION') {
      console.error('⚠️ Connection failed. Check Zoho SMTP settings.');
    }
    
    return {
      success: false,
      error: error.message,
      code: error.code
    };
  }
};

/**
 * Send appointment confirmation (for future use)
 */
const sendAppointmentConfirmation = async (appointmentData) => {
  // Similar implementation for appointments
};

module.exports = {
  sendNewClientNotification,
  sendAppointmentConfirmation
};